version: '3'
services:

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app_network
  
  backend:
    build:
      context: ./backend
    ports:
      - "1337:1337"
    environment:
      COMPOSE_HTTP_TIMEOUT: 300
      DATABASE_CLIENT: sqlite
      DATABASE_NAME: strapi
      DATABASE_FILENAME: /tmp/data.db
      DATABASE_HOST: 0.0.0.0
      DATABASE_PORT: 1337
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./data:/tmp # map local data directory to container
    restart: always
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
      - 24678:24678
    restart: always
    networks:
      - app_network
    depends_on:
      - backend
    environment:
      COMPOSE_HTTP_TIMEOUT: 300
      API_URL: http://backend:1337/api

networks:
  app_network:
    driver: bridge
